# Generated by Django 5.2.6 on 2025-11-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
