# Generated by Django 5.2.6 on 2025-11-26 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='myapp.destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('cod', 'Cash On Delivery')], max_length=100),
        ),
    ]
