# Generated by Django 5.2.6 on 2025-11-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_package_destination_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
