# Generated by Django 5.2.6 on 2025-12-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_number',
            field=models.CharField(default='01957027536', max_length=20),
        ),
    ]
